
name: urban_farming_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  image_picker: ^1.2.4
  http: ^1.6.0
  http_parser: ^4.1.2
  fl_chart: ^1.2.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  firebase_ai: ^4.0.0
  firebase_app_check: ^0.4.8
  geolocator: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
