import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

enum AppLanguage {
  english,
  hindi,
  gujarati,
  marathi,
  bengali,
  tamil,
  telugu,
  kannada,
  malayalam,
  punjabi,
  odia,
  assamese,
}

extension AppLanguageDetails on AppLanguage {
  String get code => const {
    AppLanguage.english: 'en',
    AppLanguage.hindi: 'hi',
    AppLanguage.gujarati: 'gu',
    AppLanguage.marathi: 'mr',
    AppLanguage.bengali: 'bn',
    AppLanguage.tamil: 'ta',
    AppLanguage.telugu: 'te',
    AppLanguage.kannada: 'kn',
    AppLanguage.malayalam: 'ml',
    AppLanguage.punjabi: 'pa',
    AppLanguage.odia: 'or',
    AppLanguage.assamese: 'as',
  }[this]!;

  String get displayName => const {
    AppLanguage.english: 'English',
    AppLanguage.hindi: 'हिन्दी',
    AppLanguage.gujarati: 'ગુજરાતી',
    AppLanguage.marathi: 'मराठी',
    AppLanguage.bengali: 'বাংলা',
    AppLanguage.tamil: 'தமிழ்',
    AppLanguage.telugu: 'తెలుగు',
    AppLanguage.kannada: 'ಕನ್ನಡ',
    AppLanguage.malayalam: 'മലയാളം',
    AppLanguage.punjabi: 'ਪੰਜਾਬੀ',
    AppLanguage.odia: 'ଓଡ଼ିଆ',
    AppLanguage.assamese: 'অসমীয়া',
  }[this]!;

  String get englishName => const {
    AppLanguage.english: 'English',
    AppLanguage.hindi: 'Hindi',
    AppLanguage.gujarati: 'Gujarati',
    AppLanguage.marathi: 'Marathi',
    AppLanguage.bengali: 'Bengali',
    AppLanguage.tamil: 'Tamil',
    AppLanguage.telugu: 'Telugu',
    AppLanguage.kannada: 'Kannada',
    AppLanguage.malayalam: 'Malayalam',
    AppLanguage.punjabi: 'Punjabi',
    AppLanguage.odia: 'Odia',
    AppLanguage.assamese: 'Assamese',
  }[this]!;

  static AppLanguage fromCode(String? code) {
    return AppLanguage.values.firstWhere(
      (language) => language.code == code,
      orElse: () => AppLanguage.english,
    );
  }

  static AppLanguage fromName(String? name) {
    return AppLanguage.values.firstWhere(
      (language) =>
          language.englishName.toLowerCase() == name?.toLowerCase() ||
          language.displayName == name,
      orElse: () => AppLanguage.english,
    );
  }
}

class AppLanguageService extends ChangeNotifier {
  AppLanguageService._();

  static final AppLanguageService instance = AppLanguageService._();

  AppLanguage _language = AppLanguage.english;
  bool _loaded = false;
  bool _saving = false;

  AppLanguage get language => _language;
  String get languageCode => _language.code;
  bool get isLoaded => _loaded;
  bool get isSaving => _saving;

  static const Map<String, Map<AppLanguage, String>> _translations = {
    'app_name': {
      AppLanguage.english: 'Urban Farming AI',
      AppLanguage.hindi: 'अर्बन फार्मिंग AI',
      AppLanguage.gujarati: 'અર્બન ફાર્મિંગ AI',
      AppLanguage.marathi: 'अर्बन फार्मिंग AI',
      AppLanguage.bengali: 'আরবান ফার্মিং AI',
      AppLanguage.tamil: 'நகர்ப்புற விவசாய AI',
      AppLanguage.telugu: 'అర్బన్ ఫార్మింగ్ AI',
      AppLanguage.kannada: 'ನಗರ ಕೃಷಿ AI',
      AppLanguage.malayalam: 'അർബൻ ഫാമിംഗ് AI',
      AppLanguage.punjabi: 'ਅਰਬਨ ਫਾਰਮਿੰਗ AI',
      AppLanguage.odia: 'ଅର୍ବାନ୍ ଫାର୍ମିଂ AI',
      AppLanguage.assamese: 'আৰ্বান ফাৰ্মিং AI',
    },
    'home': {
      AppLanguage.english: 'Home',
      AppLanguage.hindi: 'होम',
      AppLanguage.gujarati: 'હોમ',
      AppLanguage.marathi: 'मुख्यपृष्ठ',
      AppLanguage.bengali: 'হোম',
      AppLanguage.tamil: 'முகப்பு',
      AppLanguage.telugu: 'హోమ్',
      AppLanguage.kannada: 'ಮುಖಪುಟ',
      AppLanguage.malayalam: 'ഹോം',
      AppLanguage.punjabi: 'ਮੁੱਖ ਪੰਨਾ',
      AppLanguage.odia: 'ମୂଳପୃଷ୍ଠା',
      AppLanguage.assamese: 'মুখ্য পৃষ্ঠা',
    },
    'garden': {
      AppLanguage.english: 'Garden',
      AppLanguage.hindi: 'बगीचा',
      AppLanguage.gujarati: 'બગીચો',
      AppLanguage.marathi: 'बाग',
      AppLanguage.bengali: 'বাগান',
      AppLanguage.tamil: 'தோட்டம்',
      AppLanguage.telugu: 'తోట',
      AppLanguage.kannada: 'ತೋಟ',
      AppLanguage.malayalam: 'തോട്ടം',
      AppLanguage.punjabi: 'ਬਾਗ਼',
      AppLanguage.odia: 'ବଗିଚା',
      AppLanguage.assamese: 'বাগিচা',
    },
    'ai_advisor': {
      AppLanguage.english: 'Garden AI',
      AppLanguage.hindi: 'गार्डन AI',
      AppLanguage.gujarati: 'ગાર્ડન AI',
      AppLanguage.marathi: 'गार्डन AI',
      AppLanguage.bengali: 'বাগান AI',
      AppLanguage.tamil: 'தோட்ட AI',
      AppLanguage.telugu: 'తోట AI',
      AppLanguage.kannada: 'ತೋಟ AI',
      AppLanguage.malayalam: 'ഗാർഡൻ AI',
      AppLanguage.punjabi: 'ਬਾਗ਼ AI',
      AppLanguage.odia: 'ବଗିଚା AI',
      AppLanguage.assamese: 'বাগিচা AI',
    },
    'rewards': {
      AppLanguage.english: 'Rewards',
      AppLanguage.hindi: 'पुरस्कार',
      AppLanguage.gujarati: 'ઇનામો',
      AppLanguage.marathi: 'बक्षिसे',
      AppLanguage.bengali: 'পুরস্কার',
      AppLanguage.tamil: 'வெகுமதிகள்',
      AppLanguage.telugu: 'బహుమతులు',
      AppLanguage.kannada: 'ಬಹುಮಾನಗಳು',
      AppLanguage.malayalam: 'പ്രതിഫലങ്ങൾ',
      AppLanguage.punjabi: 'ਇਨਾਮ',
      AppLanguage.odia: 'ପୁରସ୍କାର',
      AppLanguage.assamese: 'পুৰস্কাৰ',
    },
    'profile': {
      AppLanguage.english: 'Profile',
      AppLanguage.hindi: 'प्रोफ़ाइल',
      AppLanguage.gujarati: 'પ્રોફાઇલ',
      AppLanguage.marathi: 'प्रोफाइल',
      AppLanguage.bengali: 'প্রোফাইল',
      AppLanguage.tamil: 'சுயவிவரம்',
      AppLanguage.telugu: 'ప్రొఫైల్',
      AppLanguage.kannada: 'ಪ್ರೊಫೈಲ್',
      AppLanguage.malayalam: 'പ്രൊഫൈൽ',
      AppLanguage.punjabi: 'ਪ੍ਰੋਫ਼ਾਈਲ',
      AppLanguage.odia: 'ପ୍ରୋଫାଇଲ୍',
      AppLanguage.assamese: 'প্ৰফাইল',
    },
    'settings': {
      AppLanguage.english: 'Settings',
      AppLanguage.hindi: 'सेटिंग्स',
      AppLanguage.gujarati: 'સેટિંગ્સ',
      AppLanguage.marathi: 'सेटिंग्ज',
      AppLanguage.bengali: 'সেটিংস',
      AppLanguage.tamil: 'அமைப்புகள்',
      AppLanguage.telugu: 'సెట్టింగ్‌లు',
      AppLanguage.kannada: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      AppLanguage.malayalam: 'ക്രമീകരണങ്ങൾ',
      AppLanguage.punjabi: 'ਸੈਟਿੰਗਾਂ',
      AppLanguage.odia: 'ସେଟିଂସ୍',
      AppLanguage.assamese: 'ছেটিংছ',
    },
    'language': {
      AppLanguage.english: 'Language',
      AppLanguage.hindi: 'भाषा',
      AppLanguage.gujarati: 'ભાષા',
      AppLanguage.marathi: 'भाषा',
      AppLanguage.bengali: 'ভাষা',
      AppLanguage.tamil: 'மொழி',
      AppLanguage.telugu: 'భాష',
      AppLanguage.kannada: 'ಭಾಷೆ',
      AppLanguage.malayalam: 'ഭാഷ',
      AppLanguage.punjabi: 'ਭਾਸ਼ਾ',
      AppLanguage.odia: 'ଭାଷା',
      AppLanguage.assamese: 'ভাষা',
    },
    'choose_language': {
      AppLanguage.english: 'Choose your language',
      AppLanguage.hindi: 'अपनी भाषा चुनें',
      AppLanguage.gujarati: 'તમારી ભાષા પસંદ કરો',
      AppLanguage.marathi: 'तुमची भाषा निवडा',
      AppLanguage.bengali: 'আপনার ভাষা বেছে নিন',
      AppLanguage.tamil: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      AppLanguage.telugu: 'మీ భాషను ఎంచుకోండి',
      AppLanguage.kannada: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      AppLanguage.malayalam: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      AppLanguage.punjabi: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
      AppLanguage.odia: 'ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ',
      AppLanguage.assamese: 'আপোনাৰ ভাষা বাছনি কৰক',
    },
    'choose_language_description': {
      AppLanguage.english: 'Choose the language used for supported app labels.',
      AppLanguage.hindi: 'समर्थित ऐप लेबल के लिए अपनी पसंदीदा भाषा चुनें।',
      AppLanguage.gujarati:
          'સમર્થિત એપ લેબલ માટે તમારી પસંદગીની ભાષા પસંદ કરો.',
      AppLanguage.marathi: 'समर्थित अॅप लेबलसाठी तुमची पसंतीची भाषा निवडा.',
      AppLanguage.bengali:
          'সমর্থিত অ্যাপের লেবেলের জন্য আপনার পছন্দের ভাষা বেছে নিন।',
      AppLanguage.tamil:
          'ஆதரிக்கப்படும் செயலி உரைகளுக்கான மொழியைத் தேர்ந்தெடுக்கவும்.',
      AppLanguage.telugu: 'మద్దతు ఉన్న యాప్ లేబుళ్ల కోసం మీ భాషను ఎంచుకోండి.',
      AppLanguage.kannada:
          'ಬೆಂಬಲಿತ ಆ್ಯಪ್ ಲೇಬಲ್‌ಗಳಿಗಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
      AppLanguage.malayalam:
          'പിന്തുണയ്ക്കുന്ന ആപ്പ് ലേബലുകൾക്കായി ഭാഷ തിരഞ്ഞെടുക്കുക.',
      AppLanguage.punjabi: 'ਸਮਰਥਿਤ ਐਪ ਲੇਬਲਾਂ ਲਈ ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ।',
      AppLanguage.odia: 'ସମର୍ଥିତ ଆପ୍ ଲେବଲ୍ ପାଇଁ ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ।',
      AppLanguage.assamese: 'সমৰ্থিত এপ লেবেলৰ বাবে আপোনাৰ ভাষা বাছনি কৰক।',
    },
    'save': {
      AppLanguage.english: 'Save',
      AppLanguage.hindi: 'सहेजें',
      AppLanguage.gujarati: 'સાચવો',
      AppLanguage.marathi: 'जतन करा',
      AppLanguage.bengali: 'সংরক্ষণ করুন',
      AppLanguage.tamil: 'சேமிக்கவும்',
      AppLanguage.telugu: 'సేవ్ చేయండి',
      AppLanguage.kannada: 'ಉಳಿಸಿ',
      AppLanguage.malayalam: 'സംരക്ഷിക്കുക',
      AppLanguage.punjabi: 'ਸੰਭਾਲੋ',
      AppLanguage.odia: 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
      AppLanguage.assamese: 'সংৰক্ষণ কৰক',
    },
    'cancel': {
      AppLanguage.english: 'Cancel',
      AppLanguage.hindi: 'रद्द करें',
      AppLanguage.gujarati: 'રદ કરો',
      AppLanguage.marathi: 'रद्द करा',
      AppLanguage.bengali: 'বাতিল করুন',
      AppLanguage.tamil: 'ரத்துசெய்',
      AppLanguage.telugu: 'రద్దు చేయండి',
      AppLanguage.kannada: 'ರದ್ದುಮಾಡಿ',
      AppLanguage.malayalam: 'റദ്ദാക്കുക',
      AppLanguage.punjabi: 'ਰੱਦ ਕਰੋ',
      AppLanguage.odia: 'ବାତିଲ କରନ୍ତୁ',
      AppLanguage.assamese: 'বাতিল কৰক',
    },
    'loading': {
      AppLanguage.english: 'Loading...',
      AppLanguage.hindi: 'लोड हो रहा है...',
      AppLanguage.gujarati: 'લોડ થઈ રહ્યું છે...',
      AppLanguage.marathi: 'लोड होत आहे...',
      AppLanguage.bengali: 'লোড হচ্ছে...',
      AppLanguage.tamil: 'ஏற்றப்படுகிறது...',
      AppLanguage.telugu: 'లోడ్ అవుతోంది...',
      AppLanguage.kannada: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      AppLanguage.malayalam: 'ലോഡ് ചെയ്യുന്നു...',
      AppLanguage.punjabi: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      AppLanguage.odia: 'ଲୋଡ୍ ହେଉଛି...',
      AppLanguage.assamese: 'লোড হৈ আছে...',
    },
    'error': {
      AppLanguage.english: 'Something went wrong',
      AppLanguage.hindi: 'कुछ गलत हो गया',
      AppLanguage.gujarati: 'કંઈક ખોટું થયું',
      AppLanguage.marathi: 'काहीतरी चूक झाली',
      AppLanguage.bengali: 'কিছু একটা সমস্যা হয়েছে',
      AppLanguage.tamil: 'ஏதோ தவறு ஏற்பட்டது',
      AppLanguage.telugu: 'ఏదో తప్పు జరిగింది',
      AppLanguage.kannada: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
      AppLanguage.malayalam: 'എന്തോ പിശക് സംഭവിച്ചു',
      AppLanguage.punjabi: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
      AppLanguage.odia: 'କିଛି ଭୁଲ ହୋଇଛି',
      AppLanguage.assamese: 'কিবা এটা ভুল হৈছে',
    },
    'welcome': {
      AppLanguage.english: 'Welcome back!',
      AppLanguage.hindi: 'वापसी पर स्वागत है!',
      AppLanguage.gujarati: 'ફરીથી સ્વાગત છે!',
      AppLanguage.marathi: 'पुन्हा स्वागत आहे!',
      AppLanguage.bengali: 'ফিরে আসার জন্য স্বাগতম!',
      AppLanguage.tamil: 'மீண்டும் வரவேற்கிறோம்!',
      AppLanguage.telugu: 'తిరిగి స్వాగతం!',
      AppLanguage.kannada: 'ಮತ್ತೆ ಸ್ವಾಗತ!',
      AppLanguage.malayalam: 'വീണ്ടും സ്വാഗതം!',
      AppLanguage.punjabi: 'ਜੀ ਆਇਆਂ ਨੂੰ!',
      AppLanguage.odia: 'ପୁଣିଥରେ ସ୍ୱାଗତ!',
      AppLanguage.assamese: 'পুনৰ স্বাগতম!',
    },
    'today': {
      AppLanguage.english: 'Today',
      AppLanguage.hindi: 'आज',
      AppLanguage.gujarati: 'આજે',
      AppLanguage.marathi: 'आज',
      AppLanguage.bengali: 'আজ',
      AppLanguage.tamil: 'இன்று',
      AppLanguage.telugu: 'ఈరోజు',
      AppLanguage.kannada: 'ಇಂದು',
      AppLanguage.malayalam: 'ഇന്ന്',
      AppLanguage.punjabi: 'ਅੱਜ',
      AppLanguage.odia: 'ଆଜି',
      AppLanguage.assamese: 'আজি',
    },
    'my_plants': {
      AppLanguage.english: 'My Plants',
      AppLanguage.hindi: 'मेरे पौधे',
      AppLanguage.gujarati: 'મારા છોડ',
      AppLanguage.marathi: 'माझी झाडे',
      AppLanguage.bengali: 'আমার গাছপালা',
      AppLanguage.tamil: 'எனது தாவரங்கள்',
      AppLanguage.telugu: 'నా మొక్కలు',
      AppLanguage.kannada: 'ನನ್ನ ಸಸ್ಯಗಳು',
      AppLanguage.malayalam: 'എന്റെ ചെടികൾ',
      AppLanguage.punjabi: 'ਮੇਰੇ ਪੌਦੇ',
      AppLanguage.odia: 'ମୋ ଗଛଗୁଡ଼ିକ',
      AppLanguage.assamese: 'মোৰ গছ-গছনি',
    },
    'plants': {
      AppLanguage.english: 'Plants',
      AppLanguage.hindi: 'पौधे',
      AppLanguage.gujarati: 'છોડ',
      AppLanguage.marathi: 'झाडे',
      AppLanguage.bengali: 'গাছপালা',
      AppLanguage.tamil: 'தாவரங்கள்',
      AppLanguage.telugu: 'మొక్కలు',
      AppLanguage.kannada: 'ಸಸ್ಯಗಳು',
      AppLanguage.malayalam: 'ചെടികൾ',
      AppLanguage.punjabi: 'ਪੌਦੇ',
      AppLanguage.odia: 'ଗଛଗୁଡ଼ିକ',
      AppLanguage.assamese: 'গছ-গছনি',
    },
    'view_all': {
      AppLanguage.english: 'View all',
      AppLanguage.hindi: 'सभी देखें',
      AppLanguage.gujarati: 'બધું જુઓ',
      AppLanguage.marathi: 'सर्व पहा',
      AppLanguage.bengali: 'সব দেখুন',
      AppLanguage.tamil: 'அனைத்தையும் காண்க',
      AppLanguage.telugu: 'అన్నీ చూడండి',
      AppLanguage.kannada: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      AppLanguage.malayalam: 'എല്ലാം കാണുക',
      AppLanguage.punjabi: 'ਸਭ ਦੇਖੋ',
      AppLanguage.odia: 'ସବୁ ଦେଖନ୍ତୁ',
      AppLanguage.assamese: 'সকলো চাওক',
    },
    'garden_empty': {
      AppLanguage.english: 'Your garden is empty',
      AppLanguage.hindi: 'आपका बगीचा खाली है',
      AppLanguage.gujarati: 'તમારો બગીચો ખાલી છે',
      AppLanguage.marathi: 'तुमची बाग रिकामी आहे',
      AppLanguage.bengali: 'আপনার বাগান খালি',
      AppLanguage.tamil: 'உங்கள் தோட்டம் காலியாக உள்ளது',
      AppLanguage.telugu: 'మీ తోట ఖాళీగా ఉంది',
      AppLanguage.kannada: 'ನಿಮ್ಮ ತೋಟ ಖಾಲಿಯಾಗಿದೆ',
      AppLanguage.malayalam: 'നിങ്ങളുടെ തോട്ടം ശൂന്യമാണ്',
      AppLanguage.punjabi: 'ਤੁਹਾਡਾ ਬਾਗ਼ ਖਾਲੀ ਹੈ',
      AppLanguage.odia: 'ଆପଣଙ୍କ ବଗିଚା ଖାଲି ଅଛି',
      AppLanguage.assamese: 'আপোনাৰ বাগিচা খালী',
    },
    'add_first_plant': {
      AppLanguage.english: 'Add Your First Plant',
      AppLanguage.hindi: 'अपना पहला पौधा जोड़ें',
      AppLanguage.gujarati: 'તમારો પહેલો છોડ ઉમેરો',
      AppLanguage.marathi: 'तुमचे पहिले झाड जोडा',
      AppLanguage.bengali: 'আপনার প্রথম গাছ যোগ করুন',
      AppLanguage.tamil: 'உங்கள் முதல் தாவரத்தைச் சேர்க்கவும்',
      AppLanguage.telugu: 'మీ మొదటి మొక్కను జోడించండి',
      AppLanguage.kannada: 'ನಿಮ್ಮ ಮೊದಲ ಸಸ್ಯವನ್ನು ಸೇರಿಸಿ',
      AppLanguage.malayalam: 'നിങ്ങളുടെ ആദ്യ ചെടി ചേർക്കുക',
      AppLanguage.punjabi: 'ਆਪਣਾ ਪਹਿਲਾ ਪੌਦਾ ਸ਼ਾਮਲ ਕਰੋ',
      AppLanguage.odia: 'ଆପଣଙ୍କ ପ୍ରଥମ ଗଛ ଯୋଡ଼ନ୍ତୁ',
      AppLanguage.assamese: 'আপোনাৰ প্ৰথম গছ যোগ কৰক',
    },
    'health': {
      AppLanguage.english: 'Health',
      AppLanguage.hindi: 'स्वास्थ्य',
      AppLanguage.gujarati: 'તંદુરસ્તી',
      AppLanguage.marathi: 'आरोग्य',
      AppLanguage.bengali: 'স্বাস্থ্য',
      AppLanguage.tamil: 'ஆரோக்கியம்',
      AppLanguage.telugu: 'ఆరోగ్యం',
      AppLanguage.kannada: 'ಆರೋಗ್ಯ',
      AppLanguage.malayalam: 'ആരോഗ്യം',
      AppLanguage.punjabi: 'ਸਿਹਤ',
      AppLanguage.odia: 'ସ୍ୱାସ୍ଥ୍ୟ',
      AppLanguage.assamese: 'স্বাস্থ্য',
    },
    'healthy': {
      AppLanguage.english: 'Healthy',
      AppLanguage.hindi: 'स्वस्थ',
      AppLanguage.gujarati: 'તંદુરસ્ત',
      AppLanguage.marathi: 'निरोगी',
      AppLanguage.bengali: 'সুস্থ',
      AppLanguage.tamil: 'ஆரோக்கியமானது',
      AppLanguage.telugu: 'ఆరోగ్యంగా ఉంది',
      AppLanguage.kannada: 'ಆರೋಗ್ಯಕರ',
      AppLanguage.malayalam: 'ആരോഗ്യമുള്ളത്',
      AppLanguage.punjabi: 'ਸਿਹਤਮੰਦ',
      AppLanguage.odia: 'ସୁସ୍ଥ',
      AppLanguage.assamese: 'সুস্থ',
    },
    'smart_watering': {
      AppLanguage.english: 'Smart watering',
      AppLanguage.hindi: 'स्मार्ट सिंचाई',
      AppLanguage.gujarati: 'સ્માર્ટ સિંચાઈ',
      AppLanguage.marathi: 'स्मार्ट पाणी देणे',
      AppLanguage.bengali: 'স্মার্ট জল দেওয়া',
      AppLanguage.tamil: 'சாமர்த்தியமான நீர்ப்பாசனம்',
      AppLanguage.telugu: 'స్మార్ట్ నీరు పోయడం',
      AppLanguage.kannada: 'ಸ್ಮಾರ್ಟ್ ನೀರುಹಾಕುವುದು',
      AppLanguage.malayalam: 'സ്മാർട്ട് നനയ്ക്കൽ',
      AppLanguage.punjabi: 'ਸਮਾਰਟ ਸਿੰਜਾਈ',
      AppLanguage.odia: 'ସ୍ମାର୍ଟ ଜଳସେଚନ',
      AppLanguage.assamese: 'স্মাৰ্ট পানী দিয়া',
    },
    'todays_recommendation': {
      AppLanguage.english: "Today's Recommendation",
      AppLanguage.hindi: 'आज की सलाह',
      AppLanguage.gujarati: 'આજની ભલામણ',
      AppLanguage.marathi: 'आजची शिफारस',
      AppLanguage.bengali: 'আজকের পরামর্শ',
      AppLanguage.tamil: 'இன்றைய பரிந்துரை',
      AppLanguage.telugu: 'నేటి సిఫార్సు',
      AppLanguage.kannada: 'ಇಂದಿನ ಸಲಹೆ',
      AppLanguage.malayalam: 'ഇന്നത്തെ നിർദ്ദേശം',
      AppLanguage.punjabi: 'ਅੱਜ ਦੀ ਸਿਫ਼ਾਰਸ਼',
      AppLanguage.odia: 'ଆଜିର ପରାମର୍ଶ',
      AppLanguage.assamese: 'আজিৰ পৰামৰ্শ',
    },
    'scan_plant_ai': {
      AppLanguage.english: 'Scan Plant with AI',
      AppLanguage.hindi: 'AI से पौधे को स्कैन करें',
      AppLanguage.gujarati: 'AI વડે છોડ સ્કેન કરો',
      AppLanguage.marathi: 'AI ने झाड स्कॅन करा',
      AppLanguage.bengali: 'AI দিয়ে গাছ স্ক্যান করুন',
      AppLanguage.tamil: 'AI மூலம் தாவரத்தை ஸ்கேன் செய்யவும்',
      AppLanguage.telugu: 'AIతో మొక్కను స్కాన్ చేయండి',
      AppLanguage.kannada: 'AI ಮೂಲಕ ಸಸ್ಯವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      AppLanguage.malayalam: 'AI ഉപയോഗിച്ച് ചെടി സ്കാൻ ചെയ്യുക',
      AppLanguage.punjabi: 'AI ਨਾਲ ਪੌਦਾ ਸਕੈਨ ਕਰੋ',
      AppLanguage.odia: 'AI ଦ୍ୱାରା ଗଛ ସ୍କାନ୍ କରନ୍ତୁ',
      AppLanguage.assamese: 'AI-ৰ সহায়ত গছ স্কেন কৰক',
    },
    'plant_scanner': {
      AppLanguage.english: 'Plant Scanner',
      AppLanguage.hindi: 'पौधा स्कैनर',
      AppLanguage.gujarati: 'છોડ સ્કેનર',
      AppLanguage.marathi: 'वनस्पती स्कॅनर',
      AppLanguage.bengali: 'গাছ স্ক্যানার',
      AppLanguage.tamil: 'தாவர ஸ்கேனர்',
      AppLanguage.telugu: 'మొక్క స్కానర్',
      AppLanguage.kannada: 'ಸಸ್ಯ ಸ್ಕ್ಯಾನರ್',
      AppLanguage.malayalam: 'പ്ലാന്റ് സ്കാനർ',
      AppLanguage.punjabi: 'ਪੌਦਾ ਸਕੈਨਰ',
      AppLanguage.odia: 'ଗଛ ସ୍କାନର୍',
      AppLanguage.assamese: 'গছ স্কেনাৰ',
    },
    'plant_library': {
      AppLanguage.english: 'Plant Library',
      AppLanguage.hindi: 'पौधों की लाइब्रेरी',
      AppLanguage.gujarati: 'છોડની લાઇબ્રેરી',
      AppLanguage.marathi: 'वनस्पती संग्रह',
      AppLanguage.bengali: 'গাছের লাইব্রেরি',
      AppLanguage.tamil: 'தாவர நூலகம்',
      AppLanguage.telugu: 'మొక్కల గ్రంథాలయం',
      AppLanguage.kannada: 'ಸಸ್ಯ ಗ್ರಂಥಾಲಯ',
      AppLanguage.malayalam: 'ചെടികളുടെ ലൈബ്രറി',
      AppLanguage.punjabi: 'ਪੌਦਿਆਂ ਦੀ ਲਾਇਬ੍ਰੇਰੀ',
      AppLanguage.odia: 'ଗଛ ଲାଇବ୍ରେରୀ',
      AppLanguage.assamese: 'গছৰ লাইব্ৰেৰী',
    },
    'smart_alerts': {
      AppLanguage.english: 'Smart Alerts',
      AppLanguage.hindi: 'स्मार्ट अलर्ट',
      AppLanguage.gujarati: 'સ્માર્ટ ચેતવણીઓ',
      AppLanguage.marathi: 'स्मार्ट सूचना',
      AppLanguage.bengali: 'স্মার্ট সতর্কতা',
      AppLanguage.tamil: 'ஸ்மார்ட் எச்சரிக்கைகள்',
      AppLanguage.telugu: 'స్మార్ట్ హెచ్చరికలు',
      AppLanguage.kannada: 'ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆಗಳು',
      AppLanguage.malayalam: 'സ്മാർട്ട് മുന്നറിയിപ്പുകൾ',
      AppLanguage.punjabi: 'ਸਮਾਰਟ ਚੇਤਾਵਨੀਆਂ',
      AppLanguage.odia: 'ସ୍ମାର୍ଟ ସତର୍କତା',
      AppLanguage.assamese: 'স্মাৰ্ট সতৰ্কবাণী',
    },
    'space_planner': {
      AppLanguage.english: 'Space Planner',
      AppLanguage.hindi: 'जगह योजनाकार',
      AppLanguage.gujarati: 'જગ્યા આયોજન',
      AppLanguage.marathi: 'जागा नियोजक',
      AppLanguage.bengali: 'জায়গা পরিকল্পক',
      AppLanguage.tamil: 'இடத் திட்டமிடல்',
      AppLanguage.telugu: 'స్థల ప్రణాళిక',
      AppLanguage.kannada: 'ಸ್ಥಳ ಯೋಜಕ',
      AppLanguage.malayalam: 'സ്ഥല ആസൂത്രണം',
      AppLanguage.punjabi: 'ਜਗ੍ਹਾ ਯੋਜਨਾਕਾਰ',
      AppLanguage.odia: 'ସ୍ଥାନ ଯୋଜନା',
      AppLanguage.assamese: 'ঠাই পৰিকল্পক',
    },
    'plant_recovery': {
      AppLanguage.english: 'Plant Recovery',
      AppLanguage.hindi: 'पौधे की रिकवरी',
      AppLanguage.gujarati: 'છોડની પુનઃપ્રાપ્તિ',
      AppLanguage.marathi: 'वनस्पती पुनर्प्राप्ती',
      AppLanguage.bengali: 'গাছের পুনরুদ্ধার',
      AppLanguage.tamil: 'தாவர மீட்பு',
      AppLanguage.telugu: 'మొక్క పునరుద్ధరణ',
      AppLanguage.kannada: 'ಸಸ್ಯ ಚೇತರಿಕೆ',
      AppLanguage.malayalam: 'ചെടി വീണ്ടെടുക്കൽ',
      AppLanguage.punjabi: 'ਪੌਦੇ ਦੀ ਰਿਕਵਰੀ',
      AppLanguage.odia: 'ଗଛର ପୁନରୁଦ୍ଧାର',
      AppLanguage.assamese: 'গছৰ পুনৰুদ্ধাৰ',
    },
    'harvest_tracker': {
      AppLanguage.english: 'Harvest Tracker',
      AppLanguage.hindi: 'फसल ट्रैकर',
      AppLanguage.gujarati: 'લણણી ટ્રેકર',
      AppLanguage.marathi: 'कापणी ट्रॅकर',
      AppLanguage.bengali: 'ফসল ট্র্যাকার',
      AppLanguage.tamil: 'அறுவடை கண்காணிப்பு',
      AppLanguage.telugu: 'పంట ట్రాకర్',
      AppLanguage.kannada: 'ಕೊಯ್ಲು ಟ್ರ್ಯಾಕರ್',
      AppLanguage.malayalam: 'വിളവെടുപ്പ് ട്രാക്കർ',
      AppLanguage.punjabi: 'ਵਾਢੀ ਟ੍ਰੈਕਰ',
      AppLanguage.odia: 'ଅମଳ ଟ୍ରାକର୍',
      AppLanguage.assamese: 'চপোৱা ট্ৰেকাৰ',
    },
    'weather_watering': {
      AppLanguage.english: 'Weather-Aware Watering',
      AppLanguage.hindi: 'मौसम के अनुसार पानी',
      AppLanguage.gujarati: 'હવામાન મુજબ પાણી',
      AppLanguage.marathi: 'हवामानानुसार पाणी',
      AppLanguage.bengali: 'আবহাওয়া অনুযায়ী জল দেওয়া',
      AppLanguage.tamil: 'வானிலைக்கேற்ப நீர்ப்பாசனம்',
      AppLanguage.telugu: 'వాతావరణ ఆధారిత నీరు',
      AppLanguage.kannada: 'ಹವಾಮಾನ ಆಧಾರಿತ ನೀರುಹಾಕುವುದು',
      AppLanguage.malayalam: 'കാലാവസ്ഥ അനുസരിച്ചുള്ള നനയ്ക്കൽ',
      AppLanguage.punjabi: 'ਮੌਸਮ ਅਨੁਸਾਰ ਪਾਣੀ',
      AppLanguage.odia: 'ପାଣିପାଗ ଅନୁଯାୟୀ ଜଳସେଚନ',
      AppLanguage.assamese: 'বতৰৰ অনুসৰি পানী দিয়া',
    },
    'care_planner': {
      AppLanguage.english: 'Smart Care Planner',
      AppLanguage.hindi: 'स्मार्ट देखभाल योजनाकार',
      AppLanguage.gujarati: 'સ્માર્ટ સંભાળ આયોજન',
      AppLanguage.marathi: 'स्मार्ट निगा नियोजक',
      AppLanguage.bengali: 'স্মার্ট যত্ন পরিকল্পক',
      AppLanguage.tamil: 'ஸ்மார்ட் பராமரிப்பு திட்டம்',
      AppLanguage.telugu: 'స్మార్ట్ సంరక్షణ ప్రణాళిక',
      AppLanguage.kannada: 'ಸ್ಮಾರ್ಟ್ ಆರೈಕೆ ಯೋಜಕ',
      AppLanguage.malayalam: 'സ്മാർട്ട് പരിചരണ പദ്ധതി',
      AppLanguage.punjabi: 'ਸਮਾਰਟ ਦੇਖਭਾਲ ਯੋਜਨਾਕਾਰ',
      AppLanguage.odia: 'ସ୍ମାର୍ଟ ଯତ୍ନ ଯୋଜନା',
      AppLanguage.assamese: 'স্মাৰ্ট যত্ন পৰিকল্পক',
    },
    'iot': {
      AppLanguage.english: 'Smart IoT',
      AppLanguage.hindi: 'स्मार्ट IoT',
      AppLanguage.gujarati: 'સ્માર્ટ IoT',
      AppLanguage.marathi: 'स्मार्ट IoT',
      AppLanguage.bengali: 'স্মার্ট IoT',
      AppLanguage.tamil: 'ஸ்மார்ட் IoT',
      AppLanguage.telugu: 'స్మార్ట్ IoT',
      AppLanguage.kannada: 'ಸ್ಮಾರ್ಟ್ IoT',
      AppLanguage.malayalam: 'സ്മാർട്ട് IoT',
      AppLanguage.punjabi: 'ਸਮਾਰਟ IoT',
      AppLanguage.odia: 'ସ୍ମାର୍ଟ IoT',
      AppLanguage.assamese: 'স্মাৰ্ট IoT',
    },
    'garden_tools': {
      AppLanguage.english: 'Garden Tools',
      AppLanguage.hindi: 'बगीचे के उपकरण',
      AppLanguage.gujarati: 'બગીચાનાં સાધનો',
      AppLanguage.marathi: 'बागेची साधने',
      AppLanguage.bengali: 'বাগানের সরঞ্জাম',
      AppLanguage.tamil: 'தோட்டக் கருவிகள்',
      AppLanguage.telugu: 'తోట పనిముట్లు',
      AppLanguage.kannada: 'ತೋಟದ ಉಪಕರಣಗಳು',
      AppLanguage.malayalam: 'തോട്ടത്തിലെ ഉപകരണങ്ങൾ',
      AppLanguage.punjabi: 'ਬਾਗ਼ ਦੇ ਸੰਦ',
      AppLanguage.odia: 'ବଗିଚା ଉପକରଣ',
      AppLanguage.assamese: 'বাগিচাৰ সঁজুলি',
    },
    'ask_ai': {
      AppLanguage.english: 'Ask AI',
      AppLanguage.hindi: 'AI से पूछें',
      AppLanguage.gujarati: 'AI ને પૂછો',
      AppLanguage.marathi: 'AI ला विचारा',
      AppLanguage.bengali: 'AI-কে জিজ্ঞাসা করুন',
      AppLanguage.tamil: 'AI-யிடம் கேளுங்கள்',
      AppLanguage.telugu: 'AIని అడగండి',
      AppLanguage.kannada: 'AI ಅನ್ನು ಕೇಳಿ',
      AppLanguage.malayalam: 'AI-യോട് ചോദിക്കുക',
      AppLanguage.punjabi: 'AI ਨੂੰ ਪੁੱਛੋ',
      AppLanguage.odia: 'AI କୁ ପଚାରନ୍ତୁ',
      AppLanguage.assamese: 'AI-ক সোধক',
    },
    'explore': {
      AppLanguage.english: 'Explore',
      AppLanguage.hindi: 'खोजें',
      AppLanguage.gujarati: 'શોધો',
      AppLanguage.marathi: 'शोधा',
      AppLanguage.bengali: 'অন্বেষণ করুন',
      AppLanguage.tamil: 'ஆராயுங்கள்',
      AppLanguage.telugu: 'అన్వేషించండి',
      AppLanguage.kannada: 'ಅನ್ವೇಷಿಸಿ',
      AppLanguage.malayalam: 'പര്യവേക്ഷണം ചെയ്യുക',
      AppLanguage.punjabi: 'ਖੋਜੋ',
      AppLanguage.odia: 'ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
      AppLanguage.assamese: 'অন্বেষণ কৰক',
    },
    'attention': {
      AppLanguage.english: 'Attention',
      AppLanguage.hindi: 'ध्यान दें',
      AppLanguage.gujarati: 'ધ્યાન આપો',
      AppLanguage.marathi: 'लक्ष द्या',
      AppLanguage.bengali: 'মনোযোগ',
      AppLanguage.tamil: 'கவனம்',
      AppLanguage.telugu: 'శ్రద్ధ',
      AppLanguage.kannada: 'ಗಮನ',
      AppLanguage.malayalam: 'ശ്രദ്ധ',
      AppLanguage.punjabi: 'ਧਿਆਨ',
      AppLanguage.odia: 'ଧ୍ୟାନ',
      AppLanguage.assamese: 'মনোযোগ',
    },
    'grow_recommendations': {
      AppLanguage.english: 'What Should I Grow?',
      AppLanguage.hindi: 'मैं क्या उगाऊँ?',
      AppLanguage.gujarati: 'મારે શું ઉગાડવું?',
      AppLanguage.marathi: 'मी काय लावावे?',
      AppLanguage.bengali: 'আমি কী চাষ করব?',
      AppLanguage.tamil: 'நான் எதை வளர்க்க வேண்டும்?',
      AppLanguage.telugu: 'నేను ఏమి పెంచాలి?',
      AppLanguage.kannada: 'ನಾನು ಏನು ಬೆಳೆಸಬೇಕು?',
      AppLanguage.malayalam: 'ഞാൻ എന്ത് വളർത്തണം?',
      AppLanguage.punjabi: 'ਮੈਂ ਕੀ ਉਗਾਵਾਂ?',
      AppLanguage.odia: 'ମୁଁ କ’ଣ ଚାଷ କରିବି?',
      AppLanguage.assamese: 'মই কি খেতি কৰিম?',
    },
    'ai_suggestions': {
      AppLanguage.english: 'AI suggestions',
      AppLanguage.hindi: 'AI सुझाव',
      AppLanguage.gujarati: 'AI સૂચનો',
      AppLanguage.marathi: 'AI सूचना',
      AppLanguage.bengali: 'AI পরামর্শ',
      AppLanguage.tamil: 'AI பரிந்துரைகள்',
      AppLanguage.telugu: 'AI సూచనలు',
      AppLanguage.kannada: 'AI ಸಲಹೆಗಳು',
      AppLanguage.malayalam: 'AI നിർദ്ദേശങ്ങൾ',
      AppLanguage.punjabi: 'AI ਸੁਝਾਅ',
      AppLanguage.odia: 'AI ପରାମର୍ଶ',
      AppLanguage.assamese: 'AI পৰামৰ্শ',
    },
    'live_simulation': {
      AppLanguage.english: 'Live simulation',
      AppLanguage.hindi: 'लाइव सिमुलेशन',
      AppLanguage.gujarati: 'લાઇવ સિમ્યુલેશન',
      AppLanguage.marathi: 'लाइव्ह सिम्युलेशन',
      AppLanguage.bengali: 'লাইভ সিমুলেশন',
      AppLanguage.tamil: 'நேரடி உருவகப்படுத்தல்',
      AppLanguage.telugu: 'లైవ్ సిమ్యులేషన్',
      AppLanguage.kannada: 'ಲೈವ್ ಸಿಮ್ಯುಲೇಶನ್',
      AppLanguage.malayalam: 'തത്സമയ സിമുലേഷൻ',
      AppLanguage.punjabi: 'ਲਾਈਵ ਸਿਮੂਲੇਸ਼ਨ',
      AppLanguage.odia: 'ଲାଇଭ୍ ସିମୁଲେସନ୍',
      AppLanguage.assamese: 'লাইভ ছিমুলেচন',
    },
    'achievements': {
      AppLanguage.english: 'Achievements',
      AppLanguage.hindi: 'उपलब्धियाँ',
      AppLanguage.gujarati: 'સિદ્ધિઓ',
      AppLanguage.marathi: 'उपलब्धी',
      AppLanguage.bengali: 'অর্জন',
      AppLanguage.tamil: 'சாதனைகள்',
      AppLanguage.telugu: 'విజయాలు',
      AppLanguage.kannada: 'ಸಾಧನೆಗಳು',
      AppLanguage.malayalam: 'നേട്ടങ്ങൾ',
      AppLanguage.punjabi: 'ਪ੍ਰਾਪਤੀਆਂ',
      AppLanguage.odia: 'ସଫଳତା',
      AppLanguage.assamese: 'সাফল্য',
    },
    'your_progress': {
      AppLanguage.english: 'Your progress',
      AppLanguage.hindi: 'आपकी प्रगति',
      AppLanguage.gujarati: 'તમારી પ્રગતિ',
      AppLanguage.marathi: 'तुमची प्रगती',
      AppLanguage.bengali: 'আপনার অগ্রগতি',
      AppLanguage.tamil: 'உங்கள் முன்னேற்றம்',
      AppLanguage.telugu: 'మీ పురోగతి',
      AppLanguage.kannada: 'ನಿಮ್ಮ ಪ್ರಗತಿ',
      AppLanguage.malayalam: 'നിങ്ങളുടെ പുരോഗതി',
      AppLanguage.punjabi: 'ਤੁਹਾਡੀ ਤਰੱਕੀ',
      AppLanguage.odia: 'ଆପଣଙ୍କ ପ୍ରଗତି',
      AppLanguage.assamese: 'আপোনাৰ অগ্ৰগতি',
    },
    'open_garden_tools': {
      AppLanguage.english: 'Open garden tools',
      AppLanguage.hindi: 'बगीचे के उपकरण खोलें',
      AppLanguage.gujarati: 'બગીચાનાં સાધનો ખોલો',
      AppLanguage.marathi: 'बागेची साधने उघडा',
      AppLanguage.bengali: 'বাগানের সরঞ্জাম খুলুন',
      AppLanguage.tamil: 'தோட்டக் கருவிகளைத் திறக்கவும்',
      AppLanguage.telugu: 'తోట పనిముట్లను తెరవండి',
      AppLanguage.kannada: 'ತೋಟದ ಉಪಕರಣಗಳನ್ನು ತೆರೆಯಿರಿ',
      AppLanguage.malayalam: 'തോട്ടത്തിലെ ഉപകരണങ്ങൾ തുറക്കുക',
      AppLanguage.punjabi: 'ਬਾਗ਼ ਦੇ ਸੰਦ ਖੋਲ੍ਹੋ',
      AppLanguage.odia: 'ବଗିଚା ଉପକରଣ ଖୋଲନ୍ତୁ',
      AppLanguage.assamese: 'বাগিচাৰ সঁজুলি খোলক',
    },
    'logout': {
      AppLanguage.english: 'Log out',
      AppLanguage.hindi: 'लॉग आउट',
      AppLanguage.gujarati: 'લૉગ આઉટ',
      AppLanguage.marathi: 'लॉग आउट',
      AppLanguage.bengali: 'লগ আউট',
      AppLanguage.tamil: 'வெளியேறு',
      AppLanguage.telugu: 'లాగ్ అవుట్',
      AppLanguage.kannada: 'ಲಾಗ್ ಔಟ್',
      AppLanguage.malayalam: 'ലോഗ് ഔട്ട്',
      AppLanguage.punjabi: 'ਲੌਗ ਆਉਟ',
      AppLanguage.odia: 'ଲଗ୍ ଆଉଟ୍',
      AppLanguage.assamese: 'লগ আউট',
    },
    'delete': {
      AppLanguage.english: 'Delete',
      AppLanguage.hindi: 'हटाएँ',
      AppLanguage.gujarati: 'કાઢી નાખો',
      AppLanguage.marathi: 'हटवा',
      AppLanguage.bengali: 'মুছুন',
      AppLanguage.tamil: 'நீக்கு',
      AppLanguage.telugu: 'తొలగించండి',
      AppLanguage.kannada: 'ಅಳಿಸಿ',
      AppLanguage.malayalam: 'ഇല്ലാതാക്കുക',
      AppLanguage.punjabi: 'ਮਿਟਾਓ',
      AppLanguage.odia: 'ମିଟାନ୍ତୁ',
      AppLanguage.assamese: 'মচক',
    },
    'delete_plant': {
      AppLanguage.english: 'Delete plant?',
      AppLanguage.hindi: 'पौधा हटाएँ?',
      AppLanguage.gujarati: 'છોડ કાઢી નાખવો છે?',
      AppLanguage.marathi: 'झाड हटवायचे?',
      AppLanguage.bengali: 'গাছ মুছবেন?',
      AppLanguage.tamil: 'தாவரத்தை நீக்கவா?',
      AppLanguage.telugu: 'మొక్కను తొలగించాలా?',
      AppLanguage.kannada: 'ಸಸ್ಯವನ್ನು ಅಳಿಸಬೇಕೇ?',
      AppLanguage.malayalam: 'ചെടി ഇല്ലാതാക്കണോ?',
      AppLanguage.punjabi: 'ਪੌਦਾ ਮਿਟਾਉਣਾ ਹੈ?',
      AppLanguage.odia: 'ଗଛ ମିଟାଇବେ କି?',
      AppLanguage.assamese: 'গছটো মচিবনে?',
    },
    'delete_plant_confirmation': {
      AppLanguage.english: 'This will remove this plant from your garden.',
      AppLanguage.hindi: 'इससे यह पौधा आपके बगीचे से हट जाएगा।',
      AppLanguage.gujarati: 'આ છોડ તમારા બગીચામાંથી દૂર થશે.',
      AppLanguage.marathi: 'यामुळे हे झाड तुमच्या बागेतून काढले जाईल.',
      AppLanguage.bengali: 'এতে গাছটি আপনার বাগান থেকে সরানো হবে।',
      AppLanguage.tamil:
          'இது உங்கள் தோட்டத்திலிருந்து இந்தத் தாவரத்தை அகற்றும்.',
      AppLanguage.telugu: 'ఇది మీ తోట నుండి ఈ మొక్కను తొలగిస్తుంది.',
      AppLanguage.kannada: 'ಇದು ನಿಮ್ಮ ತೋಟದಿಂದ ಈ ಸಸ್ಯವನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ.',
      AppLanguage.malayalam:
          'ഇത് നിങ്ങളുടെ തോട്ടത്തിൽ നിന്ന് ഈ ചെടി നീക്കം ചെയ്യും.',
      AppLanguage.punjabi: 'ਇਹ ਪੌਦਾ ਤੁਹਾਡੇ ਬਾਗ਼ ਵਿੱਚੋਂ ਹਟਾ ਦਿੱਤਾ ਜਾਵੇਗਾ।',
      AppLanguage.odia: 'ଏହା ଆପଣଙ୍କ ବଗିଚାରୁ ଏହି ଗଛକୁ ହଟାଇଦେବ।',
      AppLanguage.assamese: 'ইয়াৰ ফলত গছটো আপোনাৰ বাগিচাৰ পৰা আঁতৰোৱা হ’ব।',
    },
    'unable_to_load_plants': {
      AppLanguage.english: 'Unable to load your plants.',
      AppLanguage.hindi: 'आपके पौधे लोड नहीं हो सके।',
      AppLanguage.gujarati: 'તમારા છોડ લોડ થઈ શક્યા નથી.',
      AppLanguage.marathi: 'तुमची झाडे लोड करता आली नाहीत.',
      AppLanguage.bengali: 'আপনার গাছগুলি লোড করা যায়নি।',
      AppLanguage.tamil: 'உங்கள் தாவரங்களை ஏற்ற முடியவில்லை.',
      AppLanguage.telugu: 'మీ మొక్కలను లోడ్ చేయలేకపోయాం.',
      AppLanguage.kannada: 'ನಿಮ್ಮ ಸಸ್ಯಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
      AppLanguage.malayalam: 'നിങ്ങളുടെ ചെടികൾ ലോഡ് ചെയ്യാനായില്ല.',
      AppLanguage.punjabi: 'ਤੁਹਾਡੇ ਪੌਦੇ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੇ।',
      AppLanguage.odia: 'ଆପଣଙ୍କ ଗଛଗୁଡ଼ିକ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।',
      AppLanguage.assamese: 'আপোনাৰ গছ-গছনি লোড কৰিব পৰা নগ’ল।',
    },
  };

  String translate(String key) {
    return _translations[key]?[_language] ??
        _translations[key]?[AppLanguage.english] ??
        key;
  }

  String call(String key) => translate(key);

  Future<void> load() async {
    try {
      final user = FirebaseAuth.instance.currentUser;

      if (user == null) {
        _language = AppLanguage.english;
        _loaded = true;
        notifyListeners();
        return;
      }

      final snapshot = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .collection('settings')
          .doc('preferences')
          .get()
          .timeout(const Duration(seconds: 10));

      final savedCode = snapshot.data()?['language']?.toString();
      _language = AppLanguageDetails.fromCode(savedCode);
    } catch (error) {
      debugPrint('Language preference load failed: $error');
      _language = AppLanguage.english;
    } finally {
      _loaded = true;
      notifyListeners();
    }
  }

  Future<void> setLanguage(AppLanguage language) async {
    _language = language;
    notifyListeners();

    final user = FirebaseAuth.instance.currentUser;

    // Language selection should still work locally when logged out.
    if (user == null) return;

    _saving = true;
    notifyListeners();

    try {
      await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .collection('settings')
          .doc('preferences')
          .set({
            'language': language.code,
            'languageName': language.englishName,
            'languageUpdatedAt': FieldValue.serverTimestamp(),
          }, SetOptions(merge: true))
          .timeout(const Duration(seconds: 10));
    } catch (error) {
      debugPrint('Language preference save failed: $error');

      // Allow the caller to show a failure message.
      rethrow;
    } finally {
      _saving = false;
      notifyListeners();
    }
  }
}
