// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHafuG6YZkwaZ0CQ54TlmvNK-dmlLmC9w',
    appId: '1:493737465445:web:c6f2dad9300f40370ad88c',
    messagingSenderId: '493737465445',
    projectId: 'urban-farming-ai',
    authDomain: 'urban-farming-ai.firebaseapp.com',
    storageBucket: 'urban-farming-ai.firebasestorage.app',
    measurementId: 'G-9PVBST7WM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtaKT98_ybgvkV93TBKFc6i38jvIEXwo4',
    appId: '1:493737465445:android:3119b0d922bb2adb0ad88c',
    messagingSenderId: '493737465445',
    projectId: 'urban-farming-ai',
    storageBucket: 'urban-farming-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-8ulS_EBhkmYuSStULzibGOBmOEFy8IA',
    appId: '1:493737465445:ios:d40ae8cfd08636100ad88c',
    messagingSenderId: '493737465445',
    projectId: 'urban-farming-ai',
    storageBucket: 'urban-farming-ai.firebasestorage.app',
    iosBundleId: 'com.example.urbanFarmingAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-8ulS_EBhkmYuSStULzibGOBmOEFy8IA',
    appId: '1:493737465445:ios:d40ae8cfd08636100ad88c',
    messagingSenderId: '493737465445',
    projectId: 'urban-farming-ai',
    storageBucket: 'urban-farming-ai.firebasestorage.app',
    iosBundleId: 'com.example.urbanFarmingAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHafuG6YZkwaZ0CQ54TlmvNK-dmlLmC9w',
    appId: '1:493737465445:web:329827962d14fad90ad88c',
    messagingSenderId: '493737465445',
    projectId: 'urban-farming-ai',
    authDomain: 'urban-farming-ai.firebaseapp.com',
    storageBucket: 'urban-farming-ai.firebasestorage.app',
    measurementId: 'G-QL71GZ4HZF',
  );
}
